spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  jpa:
    database-platform: spring.jpa.database-platform
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true